/* Copyright (C) by OpenResty Inc. All rights reserved. */
 

#ifndef CONFIG_BPF_JIT
#define ORBPF_OVERRODE_CONFIG_BPF_JIT
#define CONFIG_BPF_JIT 1
#endif

#ifndef CONFIG_BPF_JIT_DEFAULT_ON
#define ORBPF_OVERRODE_CONFIG_BPF_JIT_DEFAULT_ON
#define CONFIG_BPF_JIT_DEFAULT_ON 1
#endif

#ifdef CONFIG_BPF_KPROBE_OVERRIDE
#define ORBPF_OVERRODE_CONFIG_BPF_KPROBE_OVERRIDE
#undef CONFIG_BPF_KPROBE_OVERRIDE
#endif

#ifdef CONFIG_BPF_LIRC_MODE2
#define ORBPF_OVERRODE_CONFIG_BPF_LIRC_MODE2
#undef CONFIG_BPF_LIRC_MODE2
#endif

#ifdef CONFIG_BPF_LSM
#define ORBPF_OVERRODE_CONFIG_BPF_LSM
#undef CONFIG_BPF_LSM
#endif

#ifndef CONFIG_BPF_SYSCALL
#define ORBPF_OVERRODE_CONFIG_BPF_SYSCALL
#define CONFIG_BPF_SYSCALL 1
#endif

#ifndef CONFIG_BPF_UNPRIV_DEFAULT_OFF
#define ORBPF_OVERRODE_CONFIG_BPF_UNPRIV_DEFAULT_OFF
#define CONFIG_BPF_UNPRIV_DEFAULT_OFF 1
#endif

#ifdef CONFIG_CGROUP_BPF
#define ORBPF_OVERRODE_CONFIG_CGROUP_BPF
#undef CONFIG_CGROUP_BPF
#endif

#ifndef CONFIG_HAVE_EBPF_JIT
#define ORBPF_OVERRODE_CONFIG_HAVE_EBPF_JIT
#define CONFIG_HAVE_EBPF_JIT 1
#endif

#ifdef CONFIG_KEYS
#define ORBPF_OVERRODE_CONFIG_KEYS
#undef CONFIG_KEYS
#endif

#ifdef CONFIG_SECURITY
#define ORBPF_OVERRODE_CONFIG_SECURITY
#undef CONFIG_SECURITY
#endif

#ifdef CONFIG_SECURITY_NETWORK
#define ORBPF_OVERRODE_CONFIG_SECURITY_NETWORK
#undef CONFIG_SECURITY_NETWORK
#endif

#ifdef CONFIG_SECURITY_PATH
#define ORBPF_OVERRODE_CONFIG_SECURITY_PATH
#undef CONFIG_SECURITY_PATH
#endif

#ifdef CONFIG_STACKTRACE
#define ORBPF_OVERRODE_CONFIG_STACKTRACE
#undef CONFIG_STACKTRACE
#endif

 















#if 1
#ifndef CONFIG_BPF_EVENTS
#define ORBPF_OVERRODE_CONFIG_BPF_EVENTS
#define CONFIG_BPF_EVENTS 1
#endif

#ifdef CONFIG_INET
#define ORBPF_OVERRODE_CONFIG_INET
#undef CONFIG_INET
#endif

#ifdef CONFIG_IPV6
#define ORBPF_OVERRODE_CONFIG_IPV6
#undef CONFIG_IPV6
#endif

#ifdef CONFIG_NET
#define ORBPF_OVERRODE_CONFIG_NET
#undef CONFIG_NET
#endif

#ifdef CONFIG_XDP_SOCKETS
#define ORBPF_OVERRODE_CONFIG_XDP_SOCKETS
#undef CONFIG_XDP_SOCKETS
#endif
#endif  