/* Copyright (C) by OpenResty Inc. All rights reserved. */
 

#ifdef ORBPF_OVERRODE_CONFIG_BPF_JIT
#undef ORBPF_OVERRODE_CONFIG_BPF_JIT
#undef CONFIG_BPF_JIT
#endif

#ifdef ORBPF_OVERRODE_CONFIG_BPF_JIT_DEFAULT_ON
#undef ORBPF_OVERRODE_CONFIG_BPF_JIT_DEFAULT_ON
#undef CONFIG_BPF_JIT_DEFAULT_ON
#endif

#ifdef ORBPF_OVERRODE_CONFIG_BPF_KPROBE_OVERRIDE
#undef ORBPF_OVERRODE_CONFIG_BPF_KPROBE_OVERRIDE
#define CONFIG_BPF_KPROBE_OVERRIDE 1
#endif

#ifdef ORBPF_OVERRODE_CONFIG_BPF_LIRC_MODE2
#undef ORBPF_OVERRODE_CONFIG_BPF_LIRC_MODE2
#define CONFIG_BPF_LIRC_MODE2 1
#endif

#ifdef ORBPF_OVERRODE_CONFIG_BPF_LSM
#undef ORBPF_OVERRODE_CONFIG_BPF_LSM
#define CONFIG_BPF_LSM 1
#endif

#ifdef ORBPF_OVERRODE_CONFIG_BPF_SYSCALL
#undef ORBPF_OVERRODE_CONFIG_BPF_SYSCALL
#undef CONFIG_BPF_SYSCALL
#endif

#ifdef ORBPF_OVERRODE_CONFIG_BPF_UNPRIV_DEFAULT_OFF
#undef ORBPF_OVERRODE_CONFIG_BPF_UNPRIV_DEFAULT_OFF
#undef CONFIG_BPF_UNPRIV_DEFAULT_OFF
#endif

#ifdef ORBPF_OVERRODE_CONFIG_CGROUP_BPF
#undef ORBPF_OVERRODE_CONFIG_CGROUP_BPF
#define CONFIG_CGROUP_BPF 1
#endif

#ifdef ORBPF_OVERRODE_CONFIG_HAVE_EBPF_JIT
#undef ORBPF_OVERRODE_CONFIG_HAVE_EBPF_JIT
#undef CONFIG_HAVE_EBPF_JIT
#endif

#ifdef ORBPF_OVERRODE_CONFIG_KEYS
#undef ORBPF_OVERRODE_CONFIG_KEYS
#define CONFIG_KEYS 1
#endif

#ifdef ORBPF_OVERRODE_CONFIG_SECURITY
#undef ORBPF_OVERRODE_CONFIG_SECURITY
#define CONFIG_SECURITY 1
#endif

#ifdef ORBPF_OVERRODE_CONFIG_SECURITY_NETWORK
#undef ORBPF_OVERRODE_CONFIG_SECURITY_NETWORK
#define CONFIG_SECURITY_NETWORK 1
#endif

#ifdef ORBPF_OVERRODE_CONFIG_SECURITY_PATH
#undef ORBPF_OVERRODE_CONFIG_SECURITY_PATH
#define CONFIG_SECURITY_PATH 1
#endif

#ifdef ORBPF_OVERRODE_CONFIG_STACKTRACE
#undef ORBPF_OVERRODE_CONFIG_STACKTRACE
#define CONFIG_STACKTRACE 1
#endif

 















#if 1
#ifdef ORBPF_OVERRODE_CONFIG_BPF_EVENTS
#undef ORBPF_OVERRODE_CONFIG_BPF_EVENTS
#undef CONFIG_BPF_EVENTS
#endif

#ifdef ORBPF_OVERRODE_CONFIG_INET
#undef ORBPF_OVERRODE_CONFIG_INET
#define CONFIG_INET 1
#endif

#ifdef ORBPF_OVERRODE_CONFIG_IPV6
#undef ORBPF_OVERRODE_CONFIG_IPV6
#define CONFIG_IPV6 1
#endif

#ifdef ORBPF_OVERRODE_CONFIG_NET
#undef ORBPF_OVERRODE_CONFIG_NET
#define CONFIG_NET 1
#endif

#ifdef ORBPF_OVERRODE_CONFIG_XDP_SOCKETS
#undef ORBPF_OVERRODE_CONFIG_XDP_SOCKETS
#define CONFIG_XDP_SOCKETS 1
#endif
#endif  